=== ITISFoundation/osparc-simcore/services/director/src/simcore_service_director/api/v0/schemas/project-v0.0.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://simcore.io/api/specs/webserver/v0/components/schemas/project-v0.0.1.json",
  "title": "simcore project",
  "description": "Description of a simcore project",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "uuid",
    "name",
    "description",
    "prjOwner",
    "accessRights",
    "creationDate",
    "lastChangeDate",
    "thumbnail",
    "workbench"
  ],
  "properties": {
    "uuid": {
      "type": "string",
      "description": "project unique identifier",
      "examples": [
        "07640335-a91f-468c-ab69-a374fa82078d",
        "9bcf8feb-c1b1-41b6-b201-639cd6ccdba8"
      ]
    },
    "name": {
      "type": "string",
      "description": "project name",
      "examples": [
        "Temporal Distortion Simulator"
      ]
    },
    "description": {
      "type": "string",
      "description": "longer one-line description about the project",
      "examples": [
        "Dabbling in temporal transitions ..."
      ]
    },
    "prjOwner": {
      "type": "string",
      "format": "idn-email",
      "description": "user email"
    },
    "accessRights": {
      "type": "object",
      "description": "object containing the GroupID as key and read/write/execution permissions as value",
      "additionalProperties": false,
      "patternProperties": {
        "^\\d+$": {
          "type": "object",
          "description": "the group id",
          "additionalProperties": false,
          "required": [
            "read",
            "write",
            "delete"
          ],
          "properties": {
            "read": {
              "type": "boolean",
              "description": "gives read access"
            },
            "write": {
              "type": "boolean",
              "description": "gives write access"
            },
            "delete": {
              "type": "boolean",
              "description": "gives deletion rights"
            }
          }
        }
      }
    },
    "creationDate": {
      "type": "string",
      "description": "project creation date",
      "pattern": "\\d{4}-(12|11|10|0?[1-9])-(31|30|[0-2]?\\d)T(2[0-3]|1\\d|0?[0-9])(:(\\d|[0-5]\\d)){2}(\\.\\d{3})?Z",
      "examples": [
        "2018-07-01T11:13:43Z"
      ]
    },
    "lastChangeDate": {
      "type": "string",
      "description": "last save date",
      "pattern": "\\d{4}-(12|11|10|0?[1-9])-(31|30|[0-2]?\\d)T(2[0-3]|1\\d|0?[0-9])(:(\\d|[0-5]\\d)){2}(\\.\\d{3})?Z",
      "examples": [
        "2018-07-01T11:13:43Z"
      ]
    },
    "thumbnail": {
      "type": "string",
      "description": "url of the latest screenshot of the project",
      "examples": [
        "https://placeimg.com/171/96/tech/grayscale/?0.jpg"
      ]
    },
    "workbench": {
      "type": "object",
      "patternProperties": {
        "^\\S+$": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "key",
            "version",
            "label",
            "position"
          ],
          "properties": {
            "key": {
              "type": "string",
              "description": "distinctive name for the node based on the docker registry path",
              "pattern": "^(simcore)/(services)(/demodec)?/(comp|dynamic|frontend)(/[^\\s/]+)+$",
              "examples": [
                "simcore/services/comp/sleeper",
                "simcore/services/dynamic/3dviewer",
                "simcore/services/frontend/file-picker"
              ]
            },
            "version": {
              "type": "string",
              "description": "semantic version number of the node",
              "pattern": "^(0|[1-9]\\d*)(\\.(0|[1-9]\\d*)){2}(-(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*)(\\.(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*))*)?(\\+[-\\da-zA-Z]+(\\.[-\\da-zA-Z-]+)*)?$",
              "examples": [
                "1.0.0",
                "0.0.1"
              ]
            },
            "label": {
              "type": "string"
            },
            "progress": {
              "type": "number",
              "maximum": 100,
              "minimum": 0,
              "description": "the node progress value"
            },
            "thumbnail": {
              "type": "string",
              "description": "url of the latest screenshot of the node",
              "examples": [
                "https://placeimg.com/171/96/tech/grayscale/?0.jpg"
              ]
            },
            "inputs": {
              "type": "object",
              "description": "values of input properties",
              "patternProperties": {
                "^[-_a-zA-Z0-9]+$": {
                  "oneOf": [
                    {
                      "type": [
                        "integer",
                        "boolean",
                        "string",
                        "number",
                        "null"
                      ]
                    },
                    {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "nodeUuid",
                        "output"
                      ],
                      "properties": {
                        "nodeUuid": {
                          "type": "string"
                        },
                        "output": {
                          "type": "string"
                        }
                      }
                    },
                    {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "store",
                        "path"
                      ],
                      "properties": {
                        "store": {
                          "type": [
                            "string",
                            "integer"
                          ]
                        },
                        "dataset": {
                          "type": "string"
                        },
                        "path": {
                          "type": "string"
                        },
                        "label": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                }
              }
            },
            "inputAccess": {
              "description": "map with key - access level pairs",
              "type": "object",
              "patternProperties": {
                "^[-_a-zA-Z0-9]+$": {
                  "type": "string",
                  "enum": [
                    "Invisible",
                    "ReadOnly",
                    "ReadAndWrite"
                  ],
                  "default": "ReadAndWrite",
                  "examples": [
                    "ReadOnly"
                  ]
                }
              }
            },
            "inputNodes": {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^\\S+$"
              },
              "description": "node IDs of where the node is connected to",
              "examples": [
                "nodeUuid1",
                "nodeUuid2"
              ]
            },
            "outputs": {
              "type": "object",
              "patternProperties": {
                "^[-_a-zA-Z0-9]+$": {
                  "oneOf": [
                    {
                      "type": [
                        "integer",
                        "boolean",
                        "string",
                        "number",
                        "null"
                      ]
                    },
                    {
                      "type": "object",
                      "additionalProperties": false,
                      "required": [
                        "store",
                        "path"
                      ],
                      "properties": {
                        "store": {
                          "type": [
                            "string",
                            "integer"
                          ]
                        },
                        "dataset": {
                          "type": "string"
                        },
                        "path": {
                          "type": "string"
                        },
                        "label": {
                          "type": "string"
                        }
                      }
                    }
                  ]
                }
              }
            },
            "outputNode": {
              "type": "boolean",
              "deprecated": true
            },
            "outputNodes": {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^\\S+$"
              },
              "description": "Used in group-nodes. Node IDs of those connected to the output",
              "examples": [
                "nodeUuid1",
                "nodeUuid2"
              ]
            },
            "parent": {
              "type": [
                "string",
                "null"
              ],
              "pattern": "^\\S+$",
              "description": "Parent's (group-nodes') node ID s.",
              "examples": [
                "nodeUuid1",
                "nodeUuid2"
              ]
            },
            "position": {
              "type": "object",
              "additionalProperties": false,
              "required": [
                "x",
                "y"
              ],
              "properties": {
                "x": {
                  "type": "integer"
                },
                "y": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "dev": {
      "type": "object",
      "description": "object used for development purposes only"
    }
  }
}

=== ITISFoundation/osparc-simcore/services/web/server/tests/data/fake-template-projects.isan.paraview.json
{
  "uuid": "de2578c5-431e-4d5e-b80e-401c8066781f",
  "name": "ISAN: 3D Paraview",
  "description": "3D Paraview viewer with two inputs",
  "thumbnail": "",
  "prjOwner": "maiz",
  "creationDate": "2019-05-24T10:36:57.813Z",
  "lastChangeDate": " 2019-05-24T10:38:12.888Z",
  "tags": [],
  "accessRights": {},
  "workbench": {
    "de2578c5-431e-403e-865a-8c5ca30671c6": {
      "key": "simcore/services/frontend/file-picker",
      "version": "1.0.0",
      "label": "File Picker 1",
      "inputs": {},
      "inputNodes": [],
      "outputs": {
        "outFile": {
          "store": 1,
          "path": "Shared Data/HField_Big.vtk"
        }
      },
      "progress": 100,
      "position": {
        "x": 100,
        "y": 100
      }
    },
    "de2578c5-431e-421f-be24-d44d112cc5c1": {
      "key": "simcore/services/frontend/file-picker",
      "version": "1.0.0",
      "label": "File Picker 2",
      "inputs": {},
      "inputNodes": [],
      "outputs": {
        "outFile": {
          "store": 1,
          "path": "Shared Data/bunny.vtk"
        }
      },
      "progress": 100,
      "position": {
        "x": 100,
        "y": 250
      }
    },
    "de2578c5-431e-4ecd-9636-62e619a9ca69": {
      "key": "simcore/services/dynamic/3d-viewer",
      "version": "2.10.0",
      "label": "3D ParaViewer",
      "inputs": {
        "A": {
          "nodeUuid": "de2578c5-431e-403e-865a-8c5ca30671c6",
          "output": "outFile"
        },
        "B": {
          "nodeUuid": "de2578c5-431e-421f-be24-d44d112cc5c1",
          "output": "outFile"
        }
      },
      "inputNodes": [
        "de2578c5-431e-403e-865a-8c5ca30671c6",
        "de2578c5-431e-421f-be24-d44d112cc5c1"
      ],
      "outputs": {},
      "progress": 0,
      "position": {
        "x": 400,
        "y": 175
      }
    }
  }
}

=== ITISFoundation/osparc-simcore/services/web/server/tests/data/fake-template-projects.isan.ucdavis.json
{
    "uuid": "de2578c5-431e-1234-a1a7-f7d4f3a8f26b",
    "name": "ISAN: UCDavis use case: 0D",
    "description": "Colleen Clancy Single Cell solver with a file picker and PostPro viewer",
    "thumbnail": "https://placeimg.com/171/96/tech/grayscale/?18.jpg",
    "prjOwner": "foo@foo.com",
    "creationDate": "2018-10-22T09:13:13.360Z",
    "lastChangeDate": "2018-10-22T09:33:41.858Z",
    "tags": [],
    "accessRights": {},
    "workbench": {
      "de2578c5-431e-4674-b758-946151cae351": {
        "key": "simcore/services/frontend/file-picker",
        "version": "1.0.0",
        "label": "File Picker 0D",
        "inputs": {},
        "inputNodes": [],
        "outputs": {
          "outFile": {
            "store": 1,
            "path": "Shared Data/initial_WStates"
          }
        },
        "progress": 100,
        "position": {
          "x": 50,
          "y": 150
        }
      },
      "de2578c5-431e-409d-998c-c1f04de67f8b": {
        "key": "simcore/services/comp/ucdavis-singlecell-cardiac-model",
        "version": "1.0.0",
        "label": "DBP-Clancy-Rabbit-Single-Cell solver",
        "inputAccess": {
          "Na": "ReadAndWrite",
          "Kr": "ReadOnly",
          "BCL": "ReadAndWrite",
          "NBeats": "ReadOnly",
          "Ligand": "Invisible",
          "cAMKII": "Invisible"
        },
        "inputs": {
          "Na": 0,
          "Kr": 0,
          "BCL": 200,
          "NBeats": 5,
          "Ligand": 0,
          "cAMKII": "WT",
          "initfile": {
            "nodeUuid": "de2578c5-431e-4674-b758-946151cae351",
            "output": "outFile"
          }
        },
        "inputNodes": [
          "de2578c5-431e-4674-b758-946151cae351"
        ],
        "outputs": {},
        "position": {
          "x": 300,
          "y": 150
        }
      },
      "de2578c5-431e-43e7-9fda-cf9625e59986": {
        "key": "simcore/services/dynamic/cc-0d-viewer",
        "version": "2.8.0",
        "label": "cc-0d-viewer",
        "inputs": {
          "vm_1Hz": {
            "nodeUuid": "de2578c5-431e-409d-998c-c1f04de67f8b",
            "output": "out_4"
          },
          "all_results_1Hz": {
            "nodeUuid": "de2578c5-431e-409d-998c-c1f04de67f8b",
            "output": "out_1"
          }
        },
        "inputNodes": [
          "de2578c5-431e-409d-998c-c1f04de67f8b"
        ],
        "outputs": {},
        "position": {
          "x": 550,
          "y": 150
        }
      }
    }
  }

=== ITISFoundation/osparc-simcore/services/storage/tests/data/projects_with_data.json
[
  {
    "uuid": "5a6d7f24-ee9a-4112-bca2-85a8ca49234a",
    "name": "ISAN2019: 3D Paraview",
    "description": "3D Paraview viewer with two inputs",
    "thumbnail": "https://user-images.githubusercontent.com/33152403/60168939-073a5580-9806-11e9-8dad-8a7caa3eb5ab.png",
    "prjOwner": "",
    "creationDate": "2019-06-06 14:33:43.065",
    "lastChangeDate": "2019-06-06 14:33:44.747",
    "accessRights": {},
    "workbench": {
      "de2578c5-431e-5753-af37-e6aec8120bf2": {
        "key": "simcore/services/frontend/file-picker",
        "version": "1.0.0",
        "label": "File Picker 1",
        "inputs": {},
        "inputNodes": [],
        "outputs": {
          "outFile": {
            "store": 1,
            "path": "Shared Data/HField_Big.vtk"
          }
        },
        "progress": 100,
        "position": {
          "x": 100,
          "y": 100
        }
      },
      "de2578c5-431e-522c-a377-dd8d7cd1265b": {
        "key": "simcore/services/frontend/file-picker",
        "version": "1.0.0",
        "label": "File Picker 2",
        "inputs": {},
        "inputNodes": [],
        "outputs": {
          "outFile": {
            "store": 1,
            "path": "Shared Data/bunny.vtk"
          }
        },
        "progress": 100,
        "position": {
          "x": 100,
          "y": 250
        }
      },
      "de2578c5-431e-9b0f-67677a20996c": {
        "key": "simcore/services/dynamic/3d-viewer",
        "version": "2.10.0",
        "label": "3D ParaViewer",
        "inputs": {
          "A": {
            "nodeUuid": "de2578c5-431e-5753-af37-e6aec8120bf2",
            "output": "outFile"
          },
          "B": {
            "nodeUuid": "de2578c5-431e-522c-a377-dd8d7cd1265b",
            "output": "outFile"
          }
        },
        "inputNodes": [
          "de2578c5-431e-5753-af37-e6aec8120bf2",
          "de2578c5-431e-522c-a377-dd8d7cd1265b"
        ],
        "outputs": {},
        "progress": 85,
        "position": {
          "x": 400,
          "y": 175
        }
      }
    }
  },
  {
    "uuid": "de2578c5-431e-5d82-b08d-d39c436ca738",
    "name": "ISAN: UCDavis use case: 0D",
    "description": "Colleen Clancy Single Cell solver with a file picker and PostPro viewer",
    "thumbnail": "https://user-images.githubusercontent.com/33152403/60168940-073a5580-9806-11e9-9a44-ae5266eeb020.png",
    "prjOwner": "",
    "creationDate": "2019-06-06 14:33:51.94",
    "lastChangeDate": "2019-06-06 14:33:54.329",
    "accessRights": {},
    "workbench": {
      "de2578c5-431e-59d6-b1a5-6e7b2773636b": {
        "key": "simcore/services/frontend/file-picker",
        "version": "1.0.0",
        "label": "File Picker 0D",
        "inputs": {},
        "inputNodes": [],
        "outputs": {
          "outFile": {
            "store": 1,
            "path": "Shared Data/initial_WStates"
          }
        },
        "progress": 100,
        "position": {
          "x": 50,
          "y": 150
        }
      },
      "de2578c5-431e-562f-afd1-cca5105c8844": {
        "key": "simcore/services/comp/ucdavis-singlecell-cardiac-model",
        "version": "1.0.0",
        "label": "DBP-Clancy-Rabbit-Single-Cell solver",
        "inputs": {
          "Na": 0,
          "Kr": 0,
          "BCL": 200,
          "NBeats": 5,
          "Ligand": 0,
          "cAMKII": "WT",
          "initfile": {
            "nodeUuid": "de2578c5-431e-59d6-b1a5-6e7b2773636b",
            "output": "outFile"
          }
        },
        "inputAccess": {
          "Na": "ReadAndWrite",
          "Kr": "ReadOnly",
          "BCL": "ReadAndWrite",
          "NBeats": "ReadOnly",
          "Ligand": "Invisible",
          "cAMKII": "Invisible"
        },
        "inputNodes": [
          "de2578c5-431e-59d6-b1a5-6e7b2773636b"
        ],
        "outputs": {},
        "progress": 0,
        "position": {
          "x": 300,
          "y": 150
        }
      },
      "de2578c5-431e-5fdd-9daa-cb03c51d8138": {
        "key": "simcore/services/dynamic/cc-0d-viewer",
        "version": "2.8.0",
        "label": "cc-0d-viewer",
        "inputs": {
          "vm_1Hz": {
            "nodeUuid": "de2578c5-431e-562f-afd1-cca5105c8844",
            "output": "out_4"
          },
          "all_results_1Hz": {
            "nodeUuid": "de2578c5-431e-562f-afd1-cca5105c8844",
            "output": "out_1"
          }
        },
        "inputNodes": [
          "de2578c5-431e-562f-afd1-cca5105c8844"
        ],
        "outputs": {},
        "progress": 20,
        "position": {
          "x": 550,
          "y": 150
        }
      }
    }
  }
]

=== ITISFoundation/osparc-simcore/services/web/server/tests/data/fake-template-projects.hack08.notebooks.json
{
  "uuid": "de2578c5-431e-4537-9f2d-2fbcbee4afb1",
  "name": "NIH SPARC Hackathon 2018",
  "description": "NIH SPARC Hackathon 2018 template consisting of a FilePicker, and two notebooks",
  "thumbnail": "https://placeimg.com/171/96/tech/grayscale/?18.jpg",
  "prjOwner": "foo@foo.com",
  "creationDate": "2018-12-05T21:13:13.360Z",
  "lastChangeDate": "2018-12-05T21:13:13.360Z",
  "accessRights": {},
  "workbench": {
    "de2578c5-431e-4261-b92f-7343aecaab44": {
      "key": "simcore/services/frontend/file-picker",
      "version": "1.0.0",
      "label": "File Picker",
      "inputs": {},
      "inputNodes": [],
      "outputs": {},
      "parent": null,
      "position": {
        "x": 50,
        "y": 150
      }
    },
    "de2578c5-431e-49b0-968d-a6545f9dc878": {
      "key": "simcore/services/dynamic/jupyter-scipy-notebook",
      "version": "1.7.0",
      "label": "Jupyter SciPy notebook",
      "inputs": {
        "input_1": {
          "nodeUuid": "de2578c5-431e-4261-b92f-7343aecaab44",
          "output": "outFile"
        }
      },
      "inputNodes": [
        "de2578c5-431e-4261-b92f-7343aecaab44"
      ],
      "outputs": {},
      "parent": null,
      "position": {
        "x": 300,
        "y": 150
      }
    },
    "de2578c5-431e-4a0e-bf7e-abad5e22e054": {
      "key": "simcore/services/dynamic/jupyter-base-notebook",
      "version": "1.7.0",
      "label": "Jupyter base notebook",
      "inputs": {
        "input_1": {
          "nodeUuid": "de2578c5-431e-49b0-968d-a6545f9dc878",
          "output": "output_1"
        }
      },
      "inputNodes": [
        "de2578c5-431e-49b0-968d-a6545f9dc878"
      ],
      "outputs": {},
      "parent": null,
      "position": {
        "x": 550,
        "y": 150
      }
    }
  }
}

=== ITISFoundation/osparc-simcore/services/web/server/tests/data/fake-template-projects.sleepers.json
{
  "uuid": "de2578c5-431e-4d5e-9b09-ddcc63121ef4",
  "name": "Sleepers",
  "description": "",
  "thumbnail": "",
  "prjOwner": "foo@foo.com",
  "creationDate": "2018-07-09T16:02:22Z",
  "lastChangeDate": "2018-07-09T16:02:22Z",
  "accessRights": {},
  "workbench": {
    "de2578c5-431e-4434-9504-d4a9bebeda37": {
      "key": "simcore/services/comp/itis/sleeper",
      "version": "1.0.0",
      "label": "sleeper 0",
      "inputAccess": {
        "in_1": "Invisible",
        "in_2": "ReadOnly"
      },
      "inputs": {
        "in_2": 2
      },
      "inputNodes": [],
      "outputs": {},
      "position": {
        "x": 50,
        "y": 300
      }
    },
    "de2578c5-431e-45ac-b2cd-2052ffc64608": {
      "key": "simcore/services/comp/itis/sleeper",
      "version": "1.0.0",
      "label": "sleeper 1",
      "inputs": {
        "in_1": {
          "nodeUuid": "de2578c5-431e-4434-9504-d4a9bebeda37",
          "output": "out_1"
        },
        "in_2": 2
      },
      "inputNodes": [
        "de2578c5-431e-4434-9504-d4a9bebeda37"
      ],
      "outputs": {},
      "position": {
        "x": 300,
        "y": 200
      }
    },
    "de2578c5-431e-4dae-9f64-94ab71317e99": {
      "key": "simcore/services/comp/itis/sleeper",
      "version": "1.0.0",
      "label": "sleeper 2",
      "inputs": {
        "in_1": {
          "nodeUuid": "de2578c5-431e-45ac-b2cd-2052ffc64608",
          "output": "out_1"
        },
        "in_2": {
          "nodeUuid": "de2578c5-431e-45ac-b2cd-2052ffc64608",
          "output": "out_2"
        }
      },
      "inputNodes": [
        "de2578c5-431e-45ac-b2cd-2052ffc64608"
      ],
      "outputs": {},
      "position": {
        "x": 550,
        "y": 200
      }
    },
    "de2578c5-431e-499e-86d6-9980c33dc8bb": {
      "key": "simcore/services/comp/itis/sleeper",
      "version": "1.0.0",
      "label": "sleeper 3",
      "inputs": {
        "in_2": {
          "nodeUuid": "de2578c5-431e-4434-9504-d4a9bebeda37",
          "output": "out_2"
        }
      },
      "inputNodes": [
        "de2578c5-431e-4434-9504-d4a9bebeda37"
      ],
      "outputs": {},
      "position": {
        "x": 420,
        "y": 400
      }
    },
    "de2578c5-431e-4ac7-aff6-6bb537766c2d": {
      "key": "simcore/services/comp/itis/sleeper",
      "version": "1.0.0",
      "label": "sleeper 4",
      "inputs": {
        "in_1": {
          "nodeUuid": "de2578c5-431e-4dae-9f64-94ab71317e99",
          "output": "out_1"
        },
        "in_2": {
          "nodeUuid": "de2578c5-431e-499e-86d6-9980c33dc8bb",
          "output": "out_2"
        }
      },
      "inputNodes": [
        "de2578c5-431e-4dae-9f64-94ab71317e99",
        "de2578c5-431e-499e-86d6-9980c33dc8bb"
      ],
      "outputs": {},
      "position": {
        "x": 800,
        "y": 300
      }
    }
  }
}

=== ITISFoundation/osparc-simcore/services/web/server/tests/data/fake-template-projects.isan.matward.json
{
  "uuid": "de2578c5-431e-420d-b82d-e80bfa272ebd",
  "name": "ISAN: MattWard use case",
  "description": "MattWard Solver/PostPro viewer",
  "thumbnail": "",
  "prjOwner": "MattWard@foo.com",
  "creationDate": "2019-04-30T08:52:20.937Z",
  "lastChangeDate": "2019-04-30T08:59:26.090Z",
  "tags": [],
  "accessRights": {},
  "workbench": {
    "de2578c5-431e-4021-b2ef-b2e163bfbd16": {
      "key": "simcore/services/dynamic/mattward-viewer",
      "version": "2.9.0",
      "label": "MattWard",
      "inputs": {},
      "inputNodes": [],
      "outputs": {},
      "progress": 0,
      "position": {
        "x": 100,
        "y": 100
      }
    }
  }
}
