=== ITISFoundation/osparc-simcore/api/specs/director/schemas/node-meta-v0.0.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "simcore node",
  "description": "Description of a simcore node 'class' with input and output",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "key",
    "version",
    "type",
    "name",
    "description",
    "authors",
    "contact",
    "inputs",
    "outputs"
  ],
  "properties": {
    "key": {
      "type": "string",
      "description": "distinctive name for the node based on the docker registry path",
      "pattern": "^(simcore)/(services)/(comp|dynamic|frontend)(/[\\w/-]+)+$",
      "examples": [
        "simcore/services/comp/itis/sleeper",
        "simcore/services/dynamic/3dviewer"
      ]
    },
    "integration-version": {
      "type": "string",
      "description": "integration version number",
      "pattern": "^(0|[1-9]\\d*)(\\.(0|[1-9]\\d*)){2}(-(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*)(\\.(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*))*)?(\\+[-\\da-zA-Z]+(\\.[-\\da-zA-Z-]+)*)?$",
      "examples": [
        "1.0.0"
      ]
    },
    "version": {
      "type": "string",
      "description": "service version number",
      "pattern": "^(0|[1-9]\\d*)(\\.(0|[1-9]\\d*)){2}(-(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*)(\\.(0|[1-9]\\d*|\\d*[-a-zA-Z][-\\da-zA-Z]*))*)?(\\+[-\\da-zA-Z]+(\\.[-\\da-zA-Z-]+)*)?$",
      "examples": [
        "1.0.0",
        "0.0.1"
      ]
    },
    "type": {
      "type": "string",
      "description": "service type",
      "enum": [
        "frontend",
        "computational",
        "dynamic"
      ],
      "examples": [
        "computational"
      ]
    },
    "name": {
      "type": "string",
      "description": "short, human readable name for the node",
      "examples": [
        "Fast Counter"
      ]
    },
    "thumbnail": {
      "type": "string",
      "description": "url to the thumbnail",
      "examples": [
        "https://user-images.githubusercontent.com/32800795/61083844-ff48fb00-a42c-11e9-8e63-fa2d709c8baf.png"
      ]
    },
    "badges": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "image",
          "url"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the subject",
            "examples": [
              "travis-ci",
              "coverals.io",
              "github.io"
            ]
          },
          "image": {
            "type": "string",
            "description": "Url to the shield",
            "examples": [
              "https://travis-ci.org/ITISFoundation/osparc-simcore.svg?branch=master",
              "https://coveralls.io/repos/github/ITISFoundation/osparc-simcore/badge.svg?branch=master",
              "https://img.shields.io/website-up-down-green-red/https/itisfoundation.github.io.svg?label=documentation"
            ]
          },
          "url": {
            "type": "string",
            "description": "Link to status",
            "examples": [
              "https://travis-ci.org/ITISFoundation/osparc-simcore 'State of CI: build, test and pushing images'",
              "https://coveralls.io/github/ITISFoundation/osparc-simcore?branch=master 'Test coverage'",
              "https://itisfoundation.github.io/"
            ]
          }
        }
      }
    },
    "description": {
      "type": "string",
      "description": "human readable description of the purpose of the node",
      "examples": [
        "Our best node type",
        "The mother of all nodes, makes your numbers shine!"
      ]
    },
    "authors": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "name",
          "email"
        ],
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the author",
            "examples": [
              "Sun Bak",
              "Delenn"
            ]
          },
          "email": {
            "description": "Email address",
            "type": "string",
            "format": "email",
            "examples": [
              "sun@sense.eight",
              "deleen@minbar.bab"
            ]
          },
          "affiliation": {
            "description": "Affiliation of the author",
            "type": "string",
            "examples": [
              "Sense8",
              "Babylon 5"
            ]
          }
        }
      }
    },
    "contact": {
      "type": "string",
      "format": "email",
      "description": "email to correspond to the authors about the node",
      "examples": [
        "lab@net.flix"
      ]
    },
    "inputs": {
      "type": "object",
      "description": "definition of the inputs of this node",
      "patternProperties": {
        "^[-_a-zA-Z0-9]+$": {
          "type": "object",
          "description": "all the input configurable for this service",
          "additionalProperties": false,
          "required": [
            "displayOrder",
            "label",
            "description",
            "type"
          ],
          "properties": {
            "displayOrder": {
              "description": "DEPRECATED: new display order is taken from the item position. This property will be removed.",
              "deprecated": true,
              "type": "number"
            },
            "label": {
              "type": "string",
              "description": "short name for the property",
              "examples": [
                "Age"
              ]
            },
            "description": {
              "type": "string",
              "description": "description of the property",
              "examples": [
                "Age in seconds since 1970"
              ]
            },
            "type": {
              "type": "string",
              "pattern": "^(number|integer|boolean|string|ref_contentSchema|data:([^/\\s,]+/[^/\\s,]+|\\[[^/\\s,]+/[^/\\s,]+(,[^/\\s]+/[^/,\\s]+)*\\]))$",
              "description": "data type expected on this input glob matching for data type is allowed",
              "examples": [
                "number",
                "boolean",
                "data:*/*",
                "data:text/*",
                "data:[image/jpeg,image/png]",
                "data:application/json",
                "data:application/json;schema=https://my-schema/not/really/schema.json",
                "data:application/vnd.ms-excel",
                "data:text/plain",
                "data:application/hdf5",
                "data:application/edu.ucdavis@ceclancy.xyz"
              ]
            },
            "contentSchema": {
              "title": "Content Schema",
              "description": "jsonschema of the content at this input/output. Required when type='ref_contentSchema'",
              "type": "object"
            },
            "fileToKeyMap": {
              "description": "Place the data associated with the named keys in files",
              "type": "object",
              "patternProperties": {
                ".+": {
                  "type": "string",
                  "pattern": "^[-_a-zA-Z0-9]+$"
                }
              },
              "examples": [
                {
                  "dir/input1.txt": "key_1",
                  "dir33/input2.txt": "key2"
                }
              ]
            },
            "defaultValue": {
              "description": "initial value for this input",
              "type": [
                "string",
                "number",
                "integer",
                "boolean"
              ],
              "examples": [
                "Dog",
                true
              ]
            },
            "unit": {
              "title": "Unit",
              "description": "Units of this input value, if a physical quantity",
              "type": "string"
            },
            "widget": {
              "description": "custom widget to use instead of the default one determined from the data-type",
              "anyOf": [
                {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "type"
                  ],
                  "properties": {
                    "type": {
                      "description": "type of the property",
                      "type": "string",
                      "enum": [
                        "TextArea"
                      ]
                    },
                    "minHeight": {
                      "description": "minimum Height of the textarea",
                      "type": "integer",
                      "minimum": 1
                    }
                  }
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "required": [
                    "type",
                    "structure"
                  ],
                  "properties": {
                    "type": {
                      "description": "type of the property",
                      "type": "string",
                      "enum": [
                        "SelectBox"
                      ]
                    },
                    "structure": {
                      "type": "array",
                      "minItems": 1,
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": [
                          "key",
                          "label"
                        ],
                        "properties": {
                          "key": {
                            "type": [
                              "string",
                              "boolean",
                              "number"
                            ]
                          },
                          "label": {
                            "type": "string"
                          }
                        },
                        "examples": [
                          [
                            {
                              "key": "rat",
                              "label": "The Rat"
                            },
                            {
                              "key": "dog",
                              "label": "Bello the Dog"
                            }
                          ]
                        ]
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    },
    "outputs": {
      "type": "object",
      "description": "definition of the outputs of this node",
      "patternProperties": {
        "^[-_a-zA-Z0-9]+$": {
          "type": "object",
          "description": "all the output produced by this node",
          "additionalProperties": false,
          "required": [
            "displayOrder",
            "label",
            "description",
            "type"
          ],
          "properties": {
            "displayOrder": {
              "type": "number",
              "description": "use this to numerically sort the properties for display",
              "examples": [
                1,
                -0.2
              ]
            },
            "label": {
              "type": "string",
              "description": "short name for the property",
              "examples": [
                "Age"
              ]
            },
            "description": {
              "type": "string",
              "description": "description of the property",
              "examples": [
                "Age in seconds since 1970"
              ]
            },
            "type": {
              "type": "string",
              "pattern": "^(number|integer|boolean|string|ref_contentSchema|data:[^/\\s,]+/[^/\\s,]+)$",
              "description": "data type expected on this output",
              "examples": [
                "number",
                "integer",
                "boolean",
                "string",
                "data:application/json",
                "data:application/vnd.ms-excel ",
                "data:text/plain",
                "data:application/hdf5"
              ]
            },
            "contentSchema": {
              "title": "Content Schema",
              "description": "jsonschema of this input/output. Required when type='ref_contentSchema'",
              "type": "object"
            },
            "fileToKeyMap": {
              "description": "Place the data stored in the named files and store it in the locations pointed to by the respective output key.",
              "type": "object",
              "patternProperties": {
                ".+": {
                  "type": "string",
                  "pattern": "^[-_a-zA-Z0-9]+$"
                }
              },
              "examples": [
                {
                  "dir/input1.txt": "key_1",
                  "dir33/input2.txt": "key2"
                }
              ]
            },
            "unit": {
              "title": "Unit",
              "description": "Units of the output value, if a physical quantity",
              "type": "string"
            }
          }
        }
      }
    },
    "boot-options": {
      "title": "Boot Options",
      "description": "Service defined boot options. These get injected in the service as env variables.",
      "type": "object",
      "patternProperties": {
        "^[_a-zA-Z0-9]+$": {
          "title": "BootOptionMode",
          "type": "object",
          "properties": {
            "label": {
              "title": "Label",
              "type": "string"
            },
            "description": {
              "title": "Description",
              "type": "string"
            },
            "default": {
              "title": "Default",
              "type": "string"
            },
            "items": {
              "title": "Items",
              "type": "object",
              "additionalProperties": {
                "title": "BootOptionItem",
                "type": "object",
                "properties": {
                  "label": {
                    "title": "Label",
                    "type": "string"
                  },
                  "description": {
                    "title": "Description",
                    "type": "string"
                  }
                },
                "required": [
                  "label",
                  "description"
                ]
              }
            }
          },
          "required": [
            "label",
            "description",
            "default",
            "items"
          ]
        }
      }
    }
  }
}

=== ITISFoundation/osparc-simcore/services/director-v2/tests/mocks/fake_service.json
{
  "name": "laborum Lorem ullamco minim",
  "description": "qui Lorem quis ut occaecat",
  "key": "simcore/services/frontend/sdflkjslfk---2342___23423/sdfkgjdlfkgd/sdkfjsdflgkj",
  "version": "844863.7218662994.388740048-9.127142757Xir8O6z.uPzMFCH.3399Y.214.7112.4935048219Qh4-k9LZJAA.0.18549123X+55gl.av.enudGN6.QszV6RAx3eF.VFWA3Vv7oo3.WV5Zd.K22.idGnQwZMb",
  "type": "frontend",
  "authors": [
    {
      "name": "amet sit culpa ea aliquip",
      "email": "yFIu@gHLKCpBGDqBnVsbYnHXXSvpVwbA.jfj",
      "affiliation": "laborum commodo"
    },
    {
      "name": "dolore Ut enim",
      "email": "fBiR3bMSO57CkD7@BuAXqyvUrwvMRYpFYTNjPXtiMjnZx.zl"
    },
    {
      "name": "nulla elit in",
      "email": "PNw7-63-eDIw1V@BMxLRwKVVLadFfzbKYfvBkh.fjry",
      "affiliation": "pariatur adipisicing quis do"
    },
    {
      "name": "in pariatur dolore consequat",
      "email": "jFMyPGZZV7mvA-D@uOkTdAyvlupivonJmG.wid",
      "affiliation": "magna culpa reprehenderit"
    }
  ],
  "contact": "KQsW9uarb@pMV.tlyy",
  "inputs": {
    "aMKxsZ": {
      "displayOrder": 10141230.40881309,
      "label": "aliquip anim ullamco",
      "description": "enim dolor irure",
      "type": "data:?0E/[7(#&hG*w",
      "defaultValue": -57410700,
      "widget": {
        "type": "TextArea",
        "details": {
          "minHeight": 79367234
        }
      }
    }
  },
  "outputs": {
    "GMpJ24EJc01": {
      "displayOrder": 6922615.513955772,
      "label": "voluptate cupidatat dolore nulla fugiat",
      "description": "Excepteur culpa pariatur labore laborum",
      "type": "string",
      "widget": {
        "type": "SelectBox",
        "details": {
          "structure": [
            {
              "key": "aliqua",
              "label": "sit deserunt ad"
            },
            {
              "key": "veniam aliqua consectetur",
              "label": "qui dolor"
            },
            {
              "key": true,
              "label": "do"
            },
            {
              "key": 74258899.37388414,
              "label": "laborum exercitation commodo"
            }
          ]
        }
      }
    }
  },
  "thumbnail": "https://some_thumbnail.com/askjgljlksdjflsdkj",
  "integration-version": "0.0.6-2864FLp3OFp.0.0.0.89537877",
  "badges": [
    {
      "name": "ea tempor reprehenderit",
      "image": "https://some_image.com/sdflksjfdlsk/sdksjlfkj",
      "url": "http://some_url.com/sdlfkjsdl/sdlkjsl"
    }
  ]
}

=== ITISFoundation/osparc-simcore/packages/models-library/tests/data/metadata-ascent-1.3.2.json
{
  "authors": [
    {
      "name": "Katie Zhuang",
      "email": "zhuang@test.it",
      "affiliation": "IT'IS Foundation"
    }
  ],
  "contact": "zhuang@test.it",
  "description": "ASCENT is an open source platform for simulating peripheral nerve stimulation. To download the software, visit the [ASCENT GitHub repository](https://github.com/wmglab-duke/ascent). This implementation uses a limited set of user-defined parameters to run the pipeline and will output the results of the NEURON simulations * Musselman ED, Cariello JE, Grill WM, Pelot NA. ASCENT (Automated Simulations to Characterize Electrical Nerve Thresholds): A Pipeline for Sample-Specific Computational Modeling of Electrical Stimulation of Peripheral Nerves. PLoS Comput Biol [Internet]. 2021; Available from: https://doi.org/10.1371/journal.pcbi.1009285 * Musselman ED, Cariello JE, Grill WM, Pelot NA. ASCENT (Automated Simulations to Characterize Electrical Nerve Thresholds): A Pipeline for Sample-Specific Computational Modeling of Electrical Stimulation of Peripheral Nerves. PLoS Comput Biol [Internet]. 2021, DOI: 10.5281/zenodo.5500260\n",
  "inputs": {
    "input_1": {
      "displayOrder": 1,
      "label": "Nerve Morphology",
      "description": "Choice of Vagus nerve morphology - either Rat VN or Human VN",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Nerve Morphology",
        "default": "Rat",
        "enum": [
          "Rat",
          "Human"
        ]
      }
    },
    "input_2": {
      "displayOrder": 2,
      "label": "Cuff geometry",
      "description": "45\u00b0 contact wrap monopolar cuff or 360\u00b0 contact wrap monopolar cuff or 45\u00b0 contact wrap, bipolar cuff or 360\u00b0 contact wrap, bipolar cuff \n",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Cuff Geometry",
        "default": "45\u00b0 monopolar",
        "enum": [
          "45\u00b0 monopolar",
          "360\u00b0 monopolar",
          "45\u00b0 bipolar",
          "360\u00b0 bipolar"
        ]
      }
    },
    "input_3": {
      "displayOrder": 3,
      "label": "Fiber Locations",
      "description": "centroid: one fiber location at the centroid of each fascicle wheel: 6 spokes with 2 fibers per spoke, plus the centroid; 13 fiber locations per fascicle\n",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Fiber Locations",
        "default": "wheel",
        "enum": [
          "centroid",
          "wheel"
        ]
      }
    },
    "fibers": {
      "displayOrder": 4,
      "label": "List of Fiber Diameters",
      "description": "Comma-separated list of fiber diameters (between 2 and 10), defaults units are \u03bcm. At least one value must be provided, maximum 5 values",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Fiber Diameters",
        "type": "array",
        "minItems": 1,
        "maxItems": 5,
        "default": [
          10
        ],
        "x_unit": "micro-meter",
        "items": {
          "minimum": 2,
          "maximum": 10,
          "type": "number"
        }
      }
    },
    "input_4": {
      "displayOrder": 5,
      "label": "Waveform",
      "description": "monophasic: pulse (cathodic for  monopolar  cuff;  cathodic phase  first  on  contact  closest to  recording  site  for bipolar cuff) biphasic: symmetric biphasic pulse\n",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Waveform",
        "default": "biphasic",
        "enum": [
          "monophasic",
          "biphasic"
        ]
      }
    },
    "durations": {
      "displayOrder": 6,
      "label": "List of Waveform Durations",
      "description": "Comma-separated list of pulse widths (between 0.05 and 2), default units are ms. At least one value must be provided, maximum 5 values.",
      "type": "ref_contentSchema",
      "contentSchema": {
        "title": "Waveform Durations",
        "type": "array",
        "minItems": 1,
        "maxItems": 5,
        "default": [
          0.5
        ],
        "x_unit": "milli-second",
        "items": {
          "minimum": 0.05,
          "maximum": 2.0,
          "type": "number"
        }
      }
    }
  },
  "integration-version": "1.0.0",
  "key": "simcore/services/comp/ascent-runner",
  "name": "ascent-runner",
  "outputs": {
    "output_1": {
      "displayOrder": 1,
      "label": "Simulation Outputs",
      "description": "Resulting thresholds from simulations.",
      "type": "data:*/*",
      "fileToKeyMap": {
        "ascent_results.zip": "output_1"
      }
    },
    "output_2": {
      "displayOrder": 1,
      "label": "Environment Variables",
      "description": "Sample number, model number and simulation number for postprocessing.",
      "type": "data:*/*",
      "fileToKeyMap": {
        "envs": "output_2"
      }
    }
  },
  "thumbnail": "https://wmglab-duke-ascent.readthedocs.io/en/latest/_images/ascent_media_release_v2.png",
  "type": "computational",
  "version": "1.3.2"
}
